name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/dockerization
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir uv
          uv pip install --system --group default  # Use default dependencies group



      - name: Run Linter (flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run Tests (pytest)
        run: |
          pip install pytest
          pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/blog-api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/blog-api:latest
            docker stop blog-api || true
            docker rm blog-api || true
            docker run -d --name blog-api -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/blog-api:latest
